spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialmedia
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
